name: FastAPI CI + SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas con cobertura
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest --cov=. --cov-report=xml

    - name: Analizar con SonarCloud (Nueva acción)
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      with:
        args: >
          -Dsonar.projectKey=GilbertoParraSuarez_TesisSalcedo
          -Dsonar.organization=GilbertoParraSuarez
          -Dsonar.python.coverage.reportPaths=coverage.xml
