name: H.U.03 - Visualización de Datos Históricos + OWASP

on:
  push:
    branches: [ "main" ]
    paths:
      - "tests/hu03/**"
      - "actions/api/services/lectura_service.py"
      - "actions/api/endpoints/lectura_router.py"
      - ".github/workflows/hu03-historical-owasp.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hu03-historical:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar tests H.U.03 - Visualización de Datos Históricos
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/hu03/test_historical_readings.py --cov=actions --cov-report=xml

    - name: OWASP Dependency-Check - Análisis de Vulnerabilidades
      uses: dependency-check/Dependency-Check_Action@v3.1.2
      with:
        project: "HU03-VisualizacionHistorica"
        scanPath: "."
        format: "HTML,JSON"
        failOnCVSS: 7.0
        outputDirectory: reports/hu03-owasp

    - name: Subir reportes de cobertura y seguridad
      uses: actions/upload-artifact@v4
      with:
        name: hu03-historical-reports
        path: |
          coverage.xml
          reports/hu03-owasp
