name: H.U.03 - Visualización de Datos Históricos

on:
  push:
    branches: [ "main" ]
    paths:
      - "tests/hu03/**"
      - "actions/api/services/lectura_service.py"
      - "actions/api/endpoints/lectura_router.py"
      - ".github/workflows/hu03-historical.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hu03-historical:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar tests H.U.03 - Visualización de Datos Históricos
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/hu03/test_historical_readings.py --cov=actions --cov-report=xml

    - name: Subir reporte de cobertura
      uses: actions/upload-artifact@v3
      with:
        name: hu03-historical-coverage
        path: coverage.xml
