name: H.U.04 - Sincronización de Datos

on:
  push:
    branches: [ "main" ]
    paths:
      - "tests/hu04/**"
      - "actions/api/services/lectura_service.py"
      - "actions/api/endpoints/lectura_router.py"
      - ".github/workflows/hu04-sync.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  sync-tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar tests H.U.04 - Sincronización de Datos
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/hu04/test_sync_readings.py --cov=actions --cov-report=xml

    - name: Subir reporte de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: hu04-sync-coverage
        path: coverage.xml
